format_directories:
  - lib/src/data_source
  - lib/src/exceptions
  - lib/src/helpers
  - test
analyze_directories:
  - lib/src/data_source
  - lib/src/exceptions
  - lib/src/helpers
  - test
coverage_exclude:
  - '**/lib/src/models/gen'