format_directories:
  - lib/src/exceptions
  - lib/src/helpers
  - lib/src/
  - test
analyze_directories:
  - lib
  - test
  - '!lib/src/models/gen'
exclude:
  - lib/src/models/gen/**
coverage_exclude:
  - 'lib/src/models/gen/**'