version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "pub"
    directory: "/api"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/."
    schedule:
      interval: "daily"

