name: fluttercon_usa_2024
description: A demo schedule app for FlutterCon USA 2024.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  fluttercon_api: 
    path: packages/fluttercon_api
  fluttercon_shared_models:
    path: api/packages/fluttercon_shared_models
  intl: ^0.19.0
  meta: ^1.12.0
  network_image_mock: ^2.1.1
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
