name: api
description: API for a demo schedule app for FlutterCon USA 2024.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  amplify_api_dart: ^0.5.3
  amplify_auth_cognito_dart: ^0.11.3
  amplify_core: ^2.3.0
  amplify_secure_storage_dart: ^0.5.1
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  fluttercon_cache:
    path: packages/fluttercon_cache
  fluttercon_data_source:
    path: packages/fluttercon_data_source
  fluttercon_shared_models:
    path: packages/fluttercon_shared_models
  hive: ^2.2.3
  path_provider: ^2.1.4
  shelf_cors_headers: ^0.1.5
  speakers_repository:
    path: packages/speakers_repository
  talks_repository:
    path: packages/talks_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
