name: Fluttercon Api

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/fluttercon_api_verify_and_test.yaml"
      - "packages/fluttercon_api/**"
      - "api/packages/fluttercon_data_source/**"
      - "api/packages/fluttercon_shared_models/**"
      - "api/packages/user_repository/**"
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "packages/fluttercon_api/**"
      - "api/packages/fluttercon_data_source/**"
      - "api/packages/fluttercon_shared_models/**"
      - "api/packages/user_repository/**"

jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main
    with:
      working_directory: packages/fluttercon_api
      dart_sdk: stable
      min_coverage: 100
